source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PSLikeEmitterView_Example', :exclusive => true do
  pod "PSLikeEmitterView", :path => "../"
end

target 'PSLikeEmitterView_Tests', :exclusive => true do
  pod "PSLikeEmitterView", :path => "../"

  
end
